name: societysphere
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.8.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  # flutter_chart: ^0.1.6
  flutter_colorpicker: ^1.1.0
  flutter_custom_clippers: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  motion_tab_bar_v2: ^0.3.0
  pie_chart: ^5.4.0
  url_launcher: ^6.3.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/splash.png
    - assets/images/notice1.jpeg
    - assets/images/facility3.jpeg
    - assets/images/visitors1.jpeg
    - assets/images/helper1.jpeg
    - assets/images/resident1.jpeg
    - assets/images/report1.jpeg
    - assets/images/character.jpeg
    - assets/images/complaint1.jpeg
    - assets/images/society1.jpg
    - assets/images/society.jpg
    - assets/balancesheet.png
    - assets/images/balance_sheet.png
    - assets/balance1.png
    - assets/building.jpg
    - assets/building1.jpg
    - assets/building2.png
    - assets/visitorsadd.png
    - assets/building21.png
    - assets/building51.png
    - assets/resident3.png
    - assets/resident6.png
    - assets/building31.png
    - assets/building71.png
    - assets/emergency1.png
    - assets/members.png
    - assets/images/sc2.jpg
    - assets/


